"""
Output module for recomp step.
"""

import json
from pathlib import Path
from typing import Dict, Any


def write_summary(stats: Dict[str, Any], out_dir: str) -> str:
    """Write a summary file and return its path."""
    out_dir_path = Path(out_dir)
    out_dir_path.mkdir(parents=True, exist_ok=True)
    summary_path = out_dir_path / "summary.json"
    with open(summary_path, "w") as f:
        json.dump(stats, f, indent=2)
    return str(summary_path)


def print_stats(engine, func_detector, xrefs, labels, strings, image):
    """Print statistics (placeholder)."""
    # Just print something to avoid breaking the build
    print("  Recomp stats: (placeholder)")


def generate_header(timestamp, git_revision, compiler, host, mode) -> str:
    """Generate a header comment."""
    return f"""/* Generated by NFSU2 Recompilation
 * Timestamp: {timestamp}
 * Git Revision: {git_revision}
 * Compiler: {compiler}
 * Host: {host}
 * Mode: {mode}
 */"""
